---
- name: Clone checkbox.io repo on BLUE
  git:
    repo: 'https://github.com/chrisparnin/checkbox.io-micro-preview.git'
    dest: "{{ ansible_env.HOME }}/checkbox.io-micro-preview"
    version: "{{ branch1 }}"
  when: group_names[0] == 'BLUE'
  
- name: Clone checkbox.io repo on GREEN
  git:
    repo: 'https://github.com/chrisparnin/checkbox.io-micro-preview.git'
    dest: "{{ ansible_env.HOME }}/checkbox.io-micro-preview"
    version: "{{ branch2 }}"
  when: group_names[0] == 'GREEN'
