---
- name: Check if tomcat exists
  stat:
    path: /tmp/tomcat
  register: tomcatExists

- name: Download tar file for tomcat installation
  get_url:
    url: {{ tomcat_tar_file_path }}
    dest: /tmp
  when: tomcatExists.stat.exists == False

- name: Extract tomcat from tar
  unarchive:
    remote_src: yes
    src: /tmp/apache-tomcat-9.0.34.tar.gz
    dest: /tmp
  when: tomcatExists.stat.exists == False

- name: Rename the extracted tar
  command: mv apache-tomcat-9.0.34 tomcat
  args:
    chdir: /tmp
  when: tomcatExists.stat.exists == False

- name: Set CATALINA_HOME environment variables
  lineinfile:
    path: /etc/environment
    line: CATALINA_HOME="/tmp/tomcat"
    state: present
    insertafter: EOF

- name: Update bash profile
  shell: . /etc/environment

- name: Copy config file
  template:
     src: tomcat-users.xml.j2  
     dest: /tmp/tomcat/conf/tomcat-users.xml
