---
- name: Set Environment variables
  become: yes
  no_log: true
  lineinfile:
    path: /etc/environment
    regexp: \'"export {{item}}"\'
    line: "export {{ item }}"
    insertafter: EOF
    state: present
  with_items: 
    - APP_PORT=3002
    - MONGO_USER={{ mongo_user }}
    - MONGO_PASSWORD={{ mongo_password }}
    - MONGO_IP=localhost
    - MONGO_PORT=27017
    - GH_USER={{ gh_user }}
    - GH_PASS={{ gh_pass }}
    - MYSQL_PASS={{ mysql_pass }}
    - GMAIL_PASS={{ gmail_pass }}
    - FROM={{ from }}
    - ID={{ id }}

- name: Restart env
  become: yes 
  shell: source /etc/environment
  args:
    executable: 
      /bin/bash