---
- name: Set Environment variables
  become: yes
  no_log: true
  lineinfile:
    path: /etc/environment
    regexp: \'"{{item}}"\'
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_items: 
    - export APP_PORT=3002
    - export MONGO_USER={{ mongo_user }}
    - MONGO_PASS={{ mongo_password }}
    - export MONGO_IP=localhost
    - export MONGO_PORT=27012

- name: Restart bashrc
  become: yes 
  shell: source /etc/environment
  args:
    executable: 
      /bin/bash