---
## Run npm install
- name: Run npm install on monitor
  become: yes
  npm: 
    path: ~/dashboard/
  when: ansible_hostname == 'monitor'

## Run npm install om checkbox and itrust
- name: Run npm install on iTrust2 and checkbox.io
  become: yes
  npm:
    path: ~/agent/
  when: ansible_hostname != 'monitor'

## Install forever on checkbox.io and iTrust
- name: Install forever
  become: yes
  npm:
    name: forever
    global: yes
    state: present

## Run forever stopall and forever start index.js ${server_name}
- name: forever stopall forever start index.js server_name
  command: "{{ item }}"
  when: ansible_hostname != 'monitor'
  with_items:
    -  forever stopall
    -  "forever start agent/index.js {{ ansible_hostname }}"
    -  forever start agent/server.js

- name: Restart redis
  systemd:
    name: redis-server
    state: restarted
  when: ansible_hostname == 'monitor'

## Run node bi/www
- name: Run forever start bin/www
  command: "{{ item }}"
  when: ansible_hostname == 'monitor'
  with_items:
    - forever stopall
    - forever start bin/www
  args:
    chdir: dashboard

  
  

