---
- name: Copy the build file
  template:
    src: build.yml.j2
    dest: ~/build.yml

- name: Copy the static analysis tester
  template:
    src: analysis.js.j2
    dest: ~/analysis.js 

- name: Create a build job
  become: yes
  shell: jenkins-jobs --flush-cache --conf jenkins_jobs.ini update build.yml

#Pause for few seconds to wait for the job to get created
- pause:
    seconds: 10

