---
- hosts: proxy:BLUE:GREEN
  gather_facts: no
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for the first time
      setup:

- hosts: proxy
  roles:
    - node
    - redis
    - proxy_code

- hosts: BLUE:GREEN
  roles:
    - clone_canary
    - node
    - npm_canary
