---
- hosts: "master,broken"
  vars_files:
    vars.yaml
  tasks:
    - name: Clone checkbox.io repo on master
      git:
        repo: 'https://github.com/chrisparnin/checkbox.io-micro-preview.git'
        dest: "{{ ansible_env.HOME }}/checkbox.io-micro-preview"
      when: group_names[0] == 'master'

    - name: Clone checkbox.io repo on broken
      git:
        repo: 'https://github.com/chrisparnin/checkbox.io-micro-preview.git'
        dest: "{{ ansible_env.HOME }}/checkbox.io-micro-preview"
        version: broken
      when: group_names[0] == 'broken'

    ## Install node
    - name: Install the gpg key for nodejs LTS
      become: yes
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      become: yes
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs and nginx
      become: yes
      apt:
        name: nodejs
        state: present

    - name: Ensure Node.js and npm are installed.
      become: yes
      apt:
        name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
        state: present
    
    ##
    - name: npm install
      become: yes
      npm:
        path: "{{ ansible_env.HOME }}/checkbox.io-micro-preview/"
    
    - name: Install forever globally
      become: yes
      npm:
        name: forever
        global: yes
        state: present

    - name: Run the code on master and broken
      command: "{{ item }}"
      with_items:
        - forever stopall
        - forever start index.js
      args:
        chdir: "{{ansible_env.HOME}}/checkbox.io-micro-preview/"