---
- hosts: "monitor,checkbox,itrust"
  gather_facts: true
  tasks: []

- hosts: monitor
  roles:
    - cp_dash
    - node
    - redis_node

- hosts: checkbox
  roles:
    - cp_agent
    - node
    - redis_node

- hosts: itrust
  roles:
    - cp_agent
    - node
    - redis_node


## run node bin/www
