---
- hosts: "monitor,checkbox.io,iTrust"
  gather_facts: true
  tasks: []

- hosts: monitor
  roles:
    - cp_dash
    - redis_node

- hosts: checkbox.io
  roles:
    - cp_agent
    - redis_node

- hosts: itrust
  roles:
    - cp_agent
    - redis_node


## run node bin/www