---
#- hosts: monitor:checkbox:itrust
#  gather_facts: true
#  tasks: []
#  tasks:
#    - debug:
#        msg: "{{ groups['monitor'][0] }}"

- hosts: monitor
  roles:
    - cp_dash
    - node
    - redis
    - npm_forever

- hosts: checkbox:itrust
  roles:
    - cp_agent
    - node
    - npm_forever

