- name: Check if repo already exists
  stat: path="{{ ansible_env.HOME }}/Deployment"
  register: repo_present

- name: Clone Deployment on proxy
  git:
    repo: https://github.com/CSC-DevOps/Deployment.git
    dest: "{{ ansible_env.HOME }}/Deployment"
  when: not repo_present.stat.exists

- name: Change serve.js
  copy:
    src: serve.js
    dest: "{{ ansible_env.HOME }}/Deployment/commands/serve.js"

- name: Copy survey.json
  copy:
    src: survey.json
    dest: "{{ ansible_env.HOME }}/Deployment/survey.json"

- name: npm install
  become: yes
  npm:
    path: "{{ ansible_env.HOME }}/Deployment/"

- name: Install npm redis and fs 
  become: yes
  npm: 
    name: "{{ item }}"
    path: "{{ ansible_env.HOME }}/Deployment/"
    state: present
  with_items:
    - redis
    - fs
    
- name: Install forever globally
  become: yes
  npm:
    name: forever
    global: yes
    state: present
  
- name: Run the code on proxyy
  command: "{{ item }}"
  with_items:
    - forever stopall
    - forever start index.js serve 
  args:
    chdir: "{{ansible_env.HOME}}/Deployment/"
  
