---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install python-pip
  become: yes
  apt:
    name: ['python-pip']
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install mysql
  include_role:
    name: mysql

- name: Checking if the path to iTrust war exists
  local_action:
    module: stat
    path: "{{ src_war_path }}"
  register: warExists

- fail:
    msg: "The war file is not found at {{ src_war_path }} and {{ warExists.stat.exists }}"
  when: warExists.stat.exists == False

- name: Install tomcat
  include_role:
    name: tomcat

- name: Remove existing iTrust.war file
  file:
    state: absent
    path: "{{ dest_war_path }}"

- name: Copy the iTrust war file to Tomcat's deployment folder
  copy:
    src: "{{ src_war_path }}"
    dest: "{{ dest_war_path }}"

- name: Restart tomcat
  service: name=tomcat state=restarted