---
#MongoDB

#Import the MongoDB repository

#Import the public key used by the package management system.
- name: Import the public key used by the PMS
  become: yes
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: Add MongoDB repository
  become: yes
  apt_repository: 
    repo: "deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    update_cache: yes

- name: install mongodb and python-pip
  become: yes
  apt: 
    pkg: ['mongodb-org','python3-pip'] 
    state: latest 
    update_cache: yes
  
- name: start mongodb
  become: yes
  systemd: 
    name: mongod 
    state: started

- name: pip install pymongo
  become: yes
  pip:
    name: pymongo
    state: present

- name: Creating user and password with readwrite roles
  become: yes
  mongodb_user:
    database: admin
    name: "{{ mongo_user }}"
    password: "{{ mongo_password }}"
    state: present
    roles: readWrite
