---
- name: Copy the build file
  copy:
    src: build_itrust.yml
    dest: ~/build_itrust.yml

- name: Create a build job
  become: yes
  shell: jenkins-jobs --flush-cache --conf jenkins_jobs.ini update build_itrust.yml

#Pause for few seconds to wait for the job to get created
- pause:
    seconds: 10