---
- name: Install redis
  apt:
    name: redis-server
    state: latest
    update_cache: yes
  become: yes
  when: ansible_hostname == 'monitor' or ansible_hostname == 'proxy'

## Edit redis.conf
- name: Change redis ip
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind 127.0.0.1 ::1'
    line: 'bind 0.0.0.0'
  when: ansible_hostname == 'monitor' or ansible_hostname == 'proxy'

- name: Restart redis
  systemd:
    name: redis-server
    state: restarted
  when: ansible_hostname == 'monitor' or ansible_hostname == 'proxy'
