---
- name: Install redis
  apt:
    name: redis-server
    state: latest
    update_cache: yes
  become: yes
  when: ansible_hostname == 'monitor' or group_names[0] == 'proxy'
  register: redis

## Edit redis.conf
- name: Change redis ip
  become: yes
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind 127.0.0.1 ::1'
    line: 'bind 0.0.0.0'
  when: ansible_hostname == 'monitor' or group_names[0] == 'proxy'

- name: Restart redis
  become: yes
  systemd:
    name: redis-server
    state: restarted
  when: (ansible_hostname == 'monitor' or group_names[0] == 'proxy')
  # async: 120
  # poll: 0 
