---
- job:
    name: M2
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git "https://kcshah:GitPassword@github.ncsu.edu/engr-csc326-staff/iTrust2-v6"
          }
          stage('Build') {
              sh 'mvn -f iTrust2/pom-data.xml process-test-classes'
              sh 'mvn clean test verify checkstyle:checkstyle'
          }
         }
