---
- name: npm install
  become: yes
  npm:
    path: "{{ ansible_env.HOME }}/checkbox.io-micro-preview/"
    
- name: Install forever globally
  become: yes
  npm:
    name: forever
    global: yes
    state: present

- name: Run the code on BLUE and GREEN 
  command: "{{ item }}"
  with_items:
    - forever stopall
    - forever start index.js
  args:
    chdir: "{{ansible_env.HOME}}/checkbox.io-micro-preview/"

- name: Copy index.js on BLUE
  templates:
    src: index1.js.j2
    dest: "{{ ansible_env.HOME }}/"
  when: group_names[0] == 'BLUE'

- name: Copy index.js on GREEN
  templates:
    src: index2.js.j2
    dest: "{{ ansible_env.HOME }}"
  when: group_names[0] == 'GREEN'

- name: Run index.js
  command: forever index.js
