---
- job:
    name: checkbox.io
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git "https://github.com/chrisparnin/checkbox.io"
          }
          stage('Build') {
              sh 'sudo systemctl start mongod'
              sh 'npm install --prefix server-side/site/'
              sh 'sudo npm install pm2 -g'
              sh 'cd server-side/site/ && pm2 start server.js &'
          }
          stage('Static Analysis') {
              sh 'sudo cp /home/vagrant/analysis.js .'
              sh 'sudo npm install esprima'
              try {
                   sh 'node analysis.js'
              }
              catch(Exception err)
              {
                   currentBuild.result = 'FAILURE'
              }
          }
          stage('Test') {
              sh 'npm test --prefix server-side/site/'
          }
          stage('Tear Down Services') {
              sh 'sudo systemctl stop mongod'
              dir ('') {
                 deleteDir()
              }
          }
         }
