---
- job:
    name: Milestone1
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git "https://github.com/chrisparnin/checkbox.io"
          }
          stage('Build') {
              sh 'sudo systemctl start mongod'
              sh 'npm install --prefix server-side/site/'
              sh 'npm install --prefix server-side/site/ pm2 -g'
              sh 'cd server-side/site/ && pm2 start server.js &'
          }
          stage('Test') {
              sh 'npm test --prefix server-side/site/'
          }
          stage('Tear Down Services') {
              sh 'sudo systemctl stop mongod'
          }
      }